### PR TITLE
NFT rewards

### PR DESCRIPTION
**Pull request by cptspacecadet**
A `DataSource` contract that can be attached to a `FundingCycle` to issue contributors ERC721 NFTs as rewards for participation. The use-case is not to replace the existing method of issuing project tokens to contributors but rather to incentivize participation by minting NTFs to some small number of early donors. This is configurable and up to 2^256 contributors can get NFTs.

Some considerations. NFTs cannot currently be redeemed for overflow. Payment and redemption params are pass-through. `DataSource` is the NFT rather than using an external contract.

### CODE REVIEW

**Comment by mejango** [comment]
I just reviewed the `NFTRewardDataSourceDelegate.sol` and the `NFTRewardTieredPriceResolver.sol`. They look great.

First pass notes:
- on the tier price resolver, we should do some validation on tiers to make sure they're passed in order and wont lead to id collisions in case of overlapping ceilings.
- should line 86 be subtracting the remainingAllowance instead of adding?
- if we wanted to relax the restriction on # of mintable NFTs (remainingAllowance, globalMintAllowance), we can do IDs that use two fewer storage slots with something that packs the tier and some info about the sender + block:
image
tradeoff is an id that reads like a random string.
- the price resolver is worth making canonical so all projects can use it without having to redeploy each time. Each variable can then be a mapping from projectId to the variable, and we'd add an `init` function thats only accessible by project owners to set those properties for their project. `validateContribution` would then also need to take in a projectId.

**Comment by mejango** [comment]
In `didPay`, check if data.projectId is _projectId.
image
:

**Comment by cptspacecadet** [comment]
Pushed the following changes:

- validate projectId
- validate tier configuration

`tokenId = tiers[i].idCeiling - tiers[i].remainingAllowance;` is subtracting so we get consecutive increasing IDs for tokens being minted.

**Comment by viraj124** [comment]
@cptspacecadet just reviewed everything looks great just a few things:
1. what is the purpose of having the admin mint IMO the admin ops can be restricted a bit just a thought
2. `unchecked` can be added in the for loops too to save some gas
3. for the open tiers due to the packing in the token id practically the no is a bit limited with just the first 8 bits being the token id can this packing be updated to ensure more items? again just a thought

**Comment by cptspacecadet** [comment]
@viraj124, thank you for the feedback

1. to allow project owner to gift NFTs to arbitrary addresses w/o contribution
2. 👍🏻
3. this is something @mejango and i came to 255 seems like a bunch of tiers, but we can add a few more bits; 10?

**Comment by viraj124** [comment]
@cptspacecadet thanks yeah sounds good

**Pull request merged**
